[package]
name = "safe_cli"
version = "0.1.0"
authors = ["hunterlester <guilfordhunter@gmail.com>"]

[dependencies]
safe_authenticator = "0.6.0"
safe_core = "0.29.0"
zxcvbn = "1.0.0"
tiny-keccak = "1.3"
console = "0.6.1"

[features]
testing = ["safe_authenticator/testing", "safe_core/testing"]
use-mock-routing = ["testing", "safe_authenticator/use-mock-routing", "safe_core/testing"]
default = ["use-mock-routing"]
