[package]
name = "safe_cli"
version = "0.1.0"
authors = ["hunterlester <guilfordhunter@gmail.com>"]
edition = "2018"

[dependencies]
zxcvbn = "1.0.0"
tiny-keccak = "1.3"
console = "0.6.1"
clap = "2.25.1"
actix-web = "0.7.18"
futures = "0.1"


[[bin]]
name = "safe_appd"
path = "src/safe_appd/bin/main.rs"

[[bin]]
name = "safe_authenticatord"
path = "src/safe_authenticatord/bin/main.rs"

[[bin]]
name = "safe_cli"
path = "src/main.rs"
